Answer.create!([
  {question_id: 11, submission_id: 31, answer: ""},
  {question_id: 11, submission_id: 31, answer: ""},
  {question_id: 10, submission_id: 32, answer: "Nope"},
  {question_id: 11, submission_id: 32, answer: ""},
  {question_id: 10, submission_id: 33, answer: "Yup"},
  {question_id: 11, submission_id: 33, answer: "Nope at all"},
  {question_id: 41, submission_id: 34, answer: "4"},
  {question_id: 42, submission_id: 34, answer: "10"},
  {question_id: 43, submission_id: 34, answer: "6"},
  {question_id: 44, submission_id: 34, answer: "6"},
  {question_id: 41, submission_id: 35, answer: "10"},
  {question_id: 42, submission_id: 35, answer: "10"},
  {question_id: 43, submission_id: 35, answer: "9"},
  {question_id: 44, submission_id: 35, answer: "10"},
  {question_id: 41, submission_id: 36, answer: "2"},
  {question_id: 42, submission_id: 36, answer: "1"},
  {question_id: 43, submission_id: 36, answer: "2"},
  {question_id: 44, submission_id: 36, answer: "2"},
  {question_id: 41, submission_id: 37, answer: "7"},
  {question_id: 42, submission_id: 37, answer: "8"},
  {question_id: 43, submission_id: 37, answer: "10"},
  {question_id: 44, submission_id: 37, answer: "7"},
  {question_id: 41, submission_id: 38, answer: "7"},
  {question_id: 42, submission_id: 38, answer: "6"},
  {question_id: 43, submission_id: 38, answer: "8"},
  {question_id: 44, submission_id: 38, answer: "2"},
  {question_id: 41, submission_id: 39, answer: "10"},
  {question_id: 42, submission_id: 39, answer: "10"},
  {question_id: 43, submission_id: 39, answer: "10"},
  {question_id: 44, submission_id: 39, answer: "10"},
  {question_id: 41, submission_id: 40, answer: "9"},
  {question_id: 42, submission_id: 40, answer: "10"},
  {question_id: 43, submission_id: 40, answer: "9"},
  {question_id: 44, submission_id: 40, answer: "9"},
  {question_id: 41, submission_id: 41, answer: "8"},
  {question_id: 42, submission_id: 41, answer: "2"},
  {question_id: 43, submission_id: 41, answer: "9"},
  {question_id: 44, submission_id: 41, answer: "8"},
  {question_id: 41, submission_id: 42, answer: "4"},
  {question_id: 42, submission_id: 42, answer: "1"},
  {question_id: 43, submission_id: 42, answer: "10"},
  {question_id: 44, submission_id: 42, answer: "4"},
  {question_id: 41, submission_id: 43, answer: "7"},
  {question_id: 42, submission_id: 43, answer: "1"},
  {question_id: 43, submission_id: 43, answer: "9"},
  {question_id: 44, submission_id: 43, answer: "8"},
  {question_id: 45, submission_id: 43, answer: "0"},
  {question_id: 45, submission_id: 42, answer: "0"},
  {question_id: 45, submission_id: 41, answer: "0"},
  {question_id: 45, submission_id: 40, answer: "0"},
  {question_id: 45, submission_id: 44, answer: "0"},
  {question_id: 45, submission_id: 45, answer: "0"},
  {question_id: 45, submission_id: 46, answer: "1"},
  {question_id: 46, submission_id: 47, answer: "1"},
  {question_id: 607, submission_id: 48, answer: "Diego"},
  {question_id: 607, submission_id: 49, answer: "Suzzy"},
  {question_id: 607, submission_id: 50, answer: "Suzzy"},
  {question_id: 607, submission_id: 51, answer: "Carl"},
  {question_id: 607, submission_id: 52, answer: "Diego"}
])
Evaluation.create!([
  {template_id: 9, teacher_id: 2, url: nil},
  {template_id: 2, teacher_id: 4, url: nil},
  {template_id: 12, teacher_id: 2, url: "C72A12D3"},
  {template_id: 9, teacher_id: 4, url: nil},
  {template_id: 9, teacher_id: 4, url: nil},
  {template_id: 14, teacher_id: 1, url: nil},
  {template_id: 12, teacher_id: 1, url: nil},
  {template_id: 14, teacher_id: 1, url: nil},
  {template_id: 9, teacher_id: 4, url: nil},
  {template_id: 9, teacher_id: 2, url: "0"},
  {template_id: 9, teacher_id: 2, url: "0"},
  {template_id: 1, teacher_id: 1, url: "E31DAA47"},
  {template_id: 15, teacher_id: 2, url: "C460CDFB"},
  {template_id: 15, teacher_id: 1, url: "AA527BAF"},
  {template_id: 15, teacher_id: 1, url: "AA527BAG"},
  {template_id: 17, teacher_id: 1, url: "C3A6D80A"},
  {template_id: 16, teacher_id: 1, url: "366FC55D"}
])
Question.create!([
  {text: "Did you like the instructor?", template_id: 12, required: false, format_type: "text"},
  {text: "Was he/she available during office hours?", template_id: 12, required: true, format_type: "1"},
  {text: "yo", template_id: 4, required: true, format_type: "ranking"},
  {text: "Is he/she a good instructor?", template_id: 1, required: true, format_type: "text"},
  {text: "Did he/she give you homework?", template_id: 1, required: false, format_type: "multipleChoice"},
  {text: "What's your fav color?", template_id: 6, required: false, format_type: "ranking"},
  {text: "Why did you take this class?", template_id: 6, required: true, format_type: "text"},
  {text: "Good teacher?", template_id: 7, required: false, format_type: "multipleChoice"},
  {text: "Bad Breath?", template_id: 7, required: true, format_type: "multipleChoice"},
  {text: "Here's another question.", template_id: 4, required: true, format_type: "ranking"},
  {text: "Was she a good teacher?", template_id: 14, required: true, format_type: "text"},
  {text: "Did she understand the material well?", template_id: 14, required: true, format_type: "multipleChoice"},
  {text: "How Knowledgable was he/she?", template_id: 17, required: true, format_type: "text"},
  {text: "Here's the first question", template_id: 17, required: true, format_type: "multipleChoice"},
  {text: "first question", template_id: 18, required: false, format_type: "text"},
  {text: "How knowledgeable was the instructor?", template_id: 12, required: true, format_type: "1"},
  {text: "Would you recommend him/her to other students?", template_id: 12, required: false, format_type: "text"},
  {text: "Did you like the accompanying course packet/book?", template_id: 12, required: true, format_type: "ranking"},
  {text: "questions 2", template_id: 21, required: false, format_type: "multipleChoice"},
  {text: "foo", template_id: 22, required: true, format_type: "multipleChoice"},
  {text: "Scale of 1 to 10, How good was the instructor?\n", template_id: 15, required: true, format_type: "scale1To10"},
  {text: "Scale of 1 to 10, how useful were the homework assignments?", template_id: 15, required: false, format_type: "scale1To10"},
  {text: "Scale of 1 to 10, How knowledgable was the intructor?", template_id: 15, required: true, format_type: "scale1To10"},
  {text: "Scale of 1 to 10, How useful were the in-class exercises?", template_id: 15, required: true, format_type: "scale1To10"},
  {text: "Did you do the homework?", template_id: 15, required: false, format_type: "boolean"},
  {text: "Would you recommend this course to colleagues?", template_id: 15, required: true, format_type: "boolean"},
  {text: "Why did you take the course?", template_id: 16, required: true, format_type: "text"},
  {text: "Who was your TA?", template_id: 15, required: true, format_type: "multipleChoice"},
  {text: "Did you go to all the classes?", template_id: 16, required: true, format_type: "boolean"},
  {text: "What did you like best about the course?", template_id: 16, required: nil, format_type: "text"}
])
QuestionOption.create!([
  {question_id: 607, text: "Carl"},
  {question_id: 607, text: "Suzzy"},
  {question_id: 607, text: "Diego"}
])
Submission.create!([
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 3, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 14, user_id: nil},
  {evaluation_id: 16, user_id: nil},
  {evaluation_id: 16, user_id: nil},
  {evaluation_id: 16, user_id: nil},
  {evaluation_id: 16, user_id: nil},
  {evaluation_id: 16, user_id: nil},
  {evaluation_id: 16, user_id: nil},
  {evaluation_id: 16, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil},
  {evaluation_id: 17, user_id: nil}
])
Teacher.create!([
  {first_name: "Joan", last_name: "Paterson", email: "jpat@gmail.com"},
  {first_name: "Tim", last_name: "Shumate", email: "timshumate@tim.com"},
  {first_name: "Sally", last_name: "Suthers", email: "stuff@you.com"},
  {first_name: "Christopher ", last_name: "Columbus", email: "chris1492@gmail.com"},
  {first_name: "Mark", last_name: "Richardson", email: "mrichardson@yahoo.com"},
  {first_name: "Mark", last_name: "Richardson", email: "mrichardson@yahoo.com"}
])
Template.create!([
  {name: "Evening Teacher Template", user_id: "2", description: "Evaluation form for teachers that work during evening classes."},
  {name: "Special Education Teacher Template", user_id: "2", description: "Teachers include John Stamos, Fred Kelly, and Sally Stu."},
  {name: "Johnny Lee's Other English Class", user_id: "2", description: nil},
  {name: "Early classes", user_id: "1", description: nil},
  {name: "Children 12-14 yrs", user_id: "1", description: "This app should be used for only children students\n"},
  {name: "Polling Graph Questions", user_id: "1", description: "This template will be filled with quant data, to setup graphs"},
  {name: "Let's Use Angular!", user_id: "1", description: "angular foo!"},
  {name: "angular again", user_id: "1", description: "stuff"}
])
