# User.create!([
#   {email: "test@test.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-08-30 08:52:00", last_sign_in_at: "2016-08-30 08:52:00", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", first_name: "", last_name: "", pro: nil},
#   {email: "markeban2@yahoo.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-08-18 00:25:11", last_sign_in_at: "2016-08-18 00:25:11", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", first_name: nil, last_name: nil, pro: nil},
#   {email: "ted@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-08-30 09:07:04", last_sign_in_at: "2016-08-30 09:07:04", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", first_name: "Bill", last_name: "& Ted", pro: nil},
#   {email: "testtest@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-08-30 18:01:55", last_sign_in_at: "2016-08-30 09:11:38", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", first_name: "test", last_name: "test", pro: nil},
#   {email: "henry@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-08-22 07:41:40", last_sign_in_at: "2016-08-22 07:41:40", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", first_name: "Mark", last_name: "Purple Hippo", pro: nil},
#   {email: "sam@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-08-30 18:04:29", last_sign_in_at: "2016-08-30 17:17:08", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", first_name: "John", last_name: "Samsung", pro: nil},
#   {email: "markeban@yahoo.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 35, current_sign_in_at: "2016-09-26 22:15:16", last_sign_in_at: "2016-09-26 22:14:20", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", first_name: "Mark", last_name: "Richardson", pro: false}
# ])
# Answer.create!([
#   {question_id: 11, submission_id: 31, answer: ""},
#   {question_id: 11, submission_id: 31, answer: ""},
#   {question_id: 10, submission_id: 32, answer: "Nope"},
#   {question_id: 11, submission_id: 32, answer: ""},
#   {question_id: 10, submission_id: 33, answer: "Yup"},
#   {question_id: 11, submission_id: 33, answer: "Nope at all"},
#   {question_id: 41, submission_id: 34, answer: "4"},
#   {question_id: 42, submission_id: 34, answer: "10"},
#   {question_id: 43, submission_id: 34, answer: "6"},
#   {question_id: 44, submission_id: 34, answer: "6"},
#   {question_id: 41, submission_id: 35, answer: "10"},
#   {question_id: 42, submission_id: 35, answer: "10"},
#   {question_id: 43, submission_id: 35, answer: "9"},
#   {question_id: 44, submission_id: 35, answer: "10"},
#   {question_id: 41, submission_id: 36, answer: "2"},
#   {question_id: 42, submission_id: 36, answer: "1"},
#   {question_id: 43, submission_id: 36, answer: "2"},
#   {question_id: 44, submission_id: 36, answer: "2"},
#   {question_id: 41, submission_id: 37, answer: "7"},
#   {question_id: 42, submission_id: 37, answer: "8"},
#   {question_id: 43, submission_id: 37, answer: "10"},
#   {question_id: 44, submission_id: 37, answer: "7"},
#   {question_id: 41, submission_id: 38, answer: "7"},
#   {question_id: 42, submission_id: 38, answer: "6"},
#   {question_id: 43, submission_id: 38, answer: "8"},
#   {question_id: 44, submission_id: 38, answer: "2"},
#   {question_id: 41, submission_id: 39, answer: "10"},
#   {question_id: 42, submission_id: 39, answer: "10"},
#   {question_id: 43, submission_id: 39, answer: "10"},
#   {question_id: 44, submission_id: 39, answer: "10"},
#   {question_id: 41, submission_id: 40, answer: "9"},
#   {question_id: 42, submission_id: 40, answer: "10"},
#   {question_id: 43, submission_id: 40, answer: "9"},
#   {question_id: 44, submission_id: 40, answer: "9"},
#   {question_id: 41, submission_id: 41, answer: "8"},
#   {question_id: 42, submission_id: 41, answer: "2"},
#   {question_id: 43, submission_id: 41, answer: "9"},
#   {question_id: 44, submission_id: 41, answer: "8"},
#   {question_id: 41, submission_id: 42, answer: "4"},
#   {question_id: 42, submission_id: 42, answer: "1"},
#   {question_id: 43, submission_id: 42, answer: "10"},
#   {question_id: 44, submission_id: 42, answer: "4"},
#   {question_id: 41, submission_id: 43, answer: "7"},
#   {question_id: 42, submission_id: 43, answer: "1"},
#   {question_id: 43, submission_id: 43, answer: "9"},
#   {question_id: 44, submission_id: 43, answer: "8"},
#   {question_id: 45, submission_id: 43, answer: "0"},
#   {question_id: 45, submission_id: 42, answer: "0"},
#   {question_id: 45, submission_id: 41, answer: "0"},
#   {question_id: 45, submission_id: 40, answer: "0"},
#   {question_id: 45, submission_id: 44, answer: "0"},
#   {question_id: 45, submission_id: 45, answer: "0"},
#   {question_id: 45, submission_id: 46, answer: "1"},
#   {question_id: 46, submission_id: 47, answer: "1"},
#   {question_id: 607, submission_id: 48, answer: "Diego"},
#   {question_id: 607, submission_id: 49, answer: "Suzzy"},
#   {question_id: 607, submission_id: 50, answer: "Suzzy"},
#   {question_id: 607, submission_id: 51, answer: "Carl"},
#   {question_id: 607, submission_id: 52, answer: "Diego"},
#   {question_id: 39, submission_id: 53, answer: "Green"},
#   {question_id: 40, submission_id: 53, answer: "0"},
#   {question_id: 41, submission_id: 53, answer: "8"},
#   {question_id: 42, submission_id: 53, answer: "to Mars"},
#   {question_id: 39, submission_id: 54, answer: "Orange"},
#   {question_id: 40, submission_id: 54, answer: "0"},
#   {question_id: 41, submission_id: 54, answer: "10"},
#   {question_id: 42, submission_id: 54, answer: "to space"},
#   {question_id: 39, submission_id: 55, answer: "Green"},
#   {question_id: 40, submission_id: 55, answer: "1"},
#   {question_id: 41, submission_id: 55, answer: "1"},
#   {question_id: 42, submission_id: 55, answer: "nowhere, I would die of the bird flu."},
#   {question_id: 39, submission_id: 56, answer: "Orange"},
#   {question_id: 40, submission_id: 56, answer: "0"},
#   {question_id: 41, submission_id: 56, answer: "8"},
#   {question_id: 42, submission_id: 56, answer: "to a tropical island"},
#   {question_id: 39, submission_id: 57, answer: "Blue"},
#   {question_id: 40, submission_id: 57, answer: "0"},
#   {question_id: 41, submission_id: 57, answer: "7"},
#   {question_id: 42, submission_id: 57, answer: "to the stratosphere "},
#   {question_id: 39, submission_id: 58, answer: nil},
#   {question_id: 40, submission_id: 58, answer: nil},
#   {question_id: 41, submission_id: 58, answer: nil},
#   {question_id: 42, submission_id: 58, answer: ""},
#   {question_id: 39, submission_id: 59, answer: nil},
#   {question_id: 40, submission_id: 59, answer: nil},
#   {question_id: 41, submission_id: 59, answer: nil},
#   {question_id: 42, submission_id: 59, answer: ""},
#   {question_id: 39, submission_id: 60, answer: "Blue"},
#   {question_id: 40, submission_id: 60, answer: nil},
#   {question_id: 41, submission_id: 60, answer: "3"},
#   {question_id: 42, submission_id: 60, answer: ""},
#   {question_id: 39, submission_id: 61, answer: "Orange"},
#   {question_id: 40, submission_id: 61, answer: "1"},
#   {question_id: 41, submission_id: 61, answer: "5"},
#   {question_id: 42, submission_id: 61, answer: "the sky!"},
#   {question_id: 39, submission_id: 62, answer: "Blue"},
#   {question_id: 40, submission_id: 62, answer: "1"},
#   {question_id: 41, submission_id: 62, answer: "10"},
#   {question_id: 42, submission_id: 62, answer: "nowhere"},
#   {question_id: 39, submission_id: 63, answer: "Orange"},
#   {question_id: 40, submission_id: 63, answer: "0"},
#   {question_id: 41, submission_id: 63, answer: "4"},
#   {question_id: 42, submission_id: 63, answer: "stuff"},
#   {question_id: 39, submission_id: 64, answer: "Blue"},
#   {question_id: 40, submission_id: 64, answer: "0"},
#   {question_id: 41, submission_id: 64, answer: "2"},
#   {question_id: 42, submission_id: 64, answer: "stuff"},
#   {question_id: 39, submission_id: 65, answer: "Orange"},
#   {question_id: 40, submission_id: 65, answer: "0"},
#   {question_id: 41, submission_id: 65, answer: "10"},
#   {question_id: 42, submission_id: 65, answer: "To the skies!"},
#   {question_id: 43, submission_id: 66, answer: "playing card games"},
#   {question_id: 44, submission_id: 66, answer: "6"},
#   {question_id: 45, submission_id: 66, answer: "0"},
#   {question_id: 43, submission_id: 67, answer: "playing card games"},
#   {question_id: 44, submission_id: 67, answer: "6"},
#   {question_id: 45, submission_id: 67, answer: "0"},
#   {question_id: 43, submission_id: 68, answer: "playing card games"},
#   {question_id: 44, submission_id: 68, answer: "6"},
#   {question_id: 45, submission_id: 68, answer: "0"},
#   {question_id: 43, submission_id: 69, answer: "playing card games"},
#   {question_id: 44, submission_id: 69, answer: "6"},
#   {question_id: 45, submission_id: 69, answer: "0"},
#   {question_id: 43, submission_id: 70, answer: "playing card games"},
#   {question_id: 44, submission_id: 70, answer: "6"},
#   {question_id: 45, submission_id: 70, answer: "0"},
#   {question_id: 43, submission_id: 71, answer: "nothing"},
#   {question_id: 44, submission_id: 71, answer: "4"},
#   {question_id: 45, submission_id: 71, answer: "1"},
#   {question_id: 43, submission_id: 72, answer: "watching a movie"},
#   {question_id: 44, submission_id: 72, answer: "7"},
#   {question_id: 45, submission_id: 72, answer: "1"},
#   {question_id: 43, submission_id: 73, answer: "watching a movie"},
#   {question_id: 44, submission_id: 73, answer: "7"},
#   {question_id: 45, submission_id: 73, answer: "1"},
#   {question_id: 43, submission_id: 74, answer: "playing card games"},
#   {question_id: 44, submission_id: 74, answer: "3"},
#   {question_id: 45, submission_id: 74, answer: "0"},
#   {question_id: 43, submission_id: 75, answer: "nothing"},
#   {question_id: 44, submission_id: 75, answer: "7"},
#   {question_id: 45, submission_id: 75, answer: "1"},
#   {question_id: 43, submission_id: 76, answer: "nothing"},
#   {question_id: 44, submission_id: 76, answer: "7"},
#   {question_id: 45, submission_id: 76, answer: "1"},
#   {question_id: 43, submission_id: 77, answer: "playing card games"},
#   {question_id: 44, submission_id: 77, answer: "5"},
#   {question_id: 45, submission_id: 77, answer: "0"},
#   {question_id: 43, submission_id: 78, answer: "playing card games"},
#   {question_id: 44, submission_id: 78, answer: "5"},
#   {question_id: 45, submission_id: 78, answer: "0"},
#   {question_id: 43, submission_id: 79, answer: "watching a movie"},
#   {question_id: 44, submission_id: 79, answer: "1"},
#   {question_id: 45, submission_id: 79, answer: "1"},
#   {question_id: 43, submission_id: 80, answer: "nothing"},
#   {question_id: 44, submission_id: 80, answer: "9"},
#   {question_id: 45, submission_id: 80, answer: "0"},
#   {question_id: 43, submission_id: 81, answer: "playing card games"},
#   {question_id: 44, submission_id: 81, answer: "7"},
#   {question_id: 45, submission_id: 81, answer: "1"},
#   {question_id: 43, submission_id: 82, answer: "watching a movie"},
#   {question_id: 44, submission_id: 82, answer: "2"},
#   {question_id: 45, submission_id: 82, answer: "0"},
#   {question_id: 43, submission_id: 83, answer: "nothing"},
#   {question_id: 44, submission_id: 83, answer: "7"},
#   {question_id: 45, submission_id: 83, answer: "0"},
#   {question_id: 43, submission_id: 84, answer: "playing card games"},
#   {question_id: 44, submission_id: 84, answer: "7"},
#   {question_id: 45, submission_id: 84, answer: "1"},
#   {question_id: 43, submission_id: 85, answer: "nothing"},
#   {question_id: 44, submission_id: 85, answer: "8"},
#   {question_id: 45, submission_id: 85, answer: "0"},
#   {question_id: 43, submission_id: 86, answer: "watching a movie"},
#   {question_id: 44, submission_id: 86, answer: "3"},
#   {question_id: 45, submission_id: 86, answer: "0"},
#   {question_id: 43, submission_id: 87, answer: "playing card games"},
#   {question_id: 44, submission_id: 87, answer: "6"},
#   {question_id: 45, submission_id: 87, answer: "1"},
#   {question_id: 43, submission_id: 88, answer: "nothing"},
#   {question_id: 44, submission_id: 88, answer: "8"},
#   {question_id: 45, submission_id: 88, answer: "0"},
#   {question_id: 43, submission_id: 89, answer: "playing card games"},
#   {question_id: 44, submission_id: 89, answer: "3"},
#   {question_id: 45, submission_id: 89, answer: "1"},
#   {question_id: 43, submission_id: 90, answer: "playing card games"},
#   {question_id: 44, submission_id: 90, answer: "4"},
#   {question_id: 45, submission_id: 90, answer: "0"},
#   {question_id: 43, submission_id: 91, answer: "nothing"},
#   {question_id: 44, submission_id: 91, answer: "10"},
#   {question_id: 45, submission_id: 91, answer: "0"},
#   {question_id: 43, submission_id: 92, answer: "nothing"},
#   {question_id: 44, submission_id: 92, answer: "9"},
#   {question_id: 45, submission_id: 92, answer: "0"},
#   {question_id: 43, submission_id: 93, answer: "playing card games"},
#   {question_id: 44, submission_id: 93, answer: "4"},
#   {question_id: 45, submission_id: 93, answer: "0"},
#   {question_id: 43, submission_id: 94, answer: "nothing"},
#   {question_id: 44, submission_id: 94, answer: "8"},
#   {question_id: 45, submission_id: 94, answer: "1"},
#   {question_id: 43, submission_id: 95, answer: "playing card games"},
#   {question_id: 44, submission_id: 95, answer: "10"},
#   {question_id: 45, submission_id: 95, answer: "0"},
#   {question_id: 11, submission_id: 96, answer: "10"},
#   {question_id: 12, submission_id: 96, answer: "10"},
#   {question_id: 46, submission_id: 96, answer: "0"},
#   {question_id: 47, submission_id: 96, answer: "1"},
#   {question_id: 48, submission_id: 96, answer: "?? I don't know"},
#   {question_id: 49, submission_id: 96, answer: "......"},
#   {question_id: 11, submission_id: 97, answer: "6"},
#   {question_id: 12, submission_id: 97, answer: "5"},
#   {question_id: 46, submission_id: 97, answer: "1"},
#   {question_id: 47, submission_id: 97, answer: "0"},
#   {question_id: 48, submission_id: 97, answer: "?? I don't know???"},
#   {question_id: 49, submission_id: 97, answer: "......"},
#   {question_id: 11, submission_id: 98, answer: "1"},
#   {question_id: 12, submission_id: 98, answer: "2"},
#   {question_id: 46, submission_id: 98, answer: "0"},
#   {question_id: 47, submission_id: 98, answer: "1"},
#   {question_id: 48, submission_id: 98, answer: "?? I don't know???"},
#   {question_id: 49, submission_id: 98, answer: "......"},
#   {question_id: 11, submission_id: 99, answer: "1"},
#   {question_id: 12, submission_id: 99, answer: "2"},
#   {question_id: 46, submission_id: 99, answer: "1"},
#   {question_id: 47, submission_id: 99, answer: "0"},
#   {question_id: 48, submission_id: 99, answer: "sdfsdf"},
#   {question_id: 49, submission_id: 99, answer: "sdfsdaf"},
#   {question_id: 11, submission_id: 100, answer: "3"},
#   {question_id: 12, submission_id: 100, answer: "3"},
#   {question_id: 46, submission_id: 100, answer: "0"},
#   {question_id: 47, submission_id: 100, answer: "1"},
#   {question_id: 48, submission_id: 100, answer: "sdfsdfsdfsdf"},
#   {question_id: 49, submission_id: 100, answer: "sdfsdafsdfds"},
#   {question_id: 11, submission_id: 101, answer: "8"},
#   {question_id: 12, submission_id: 101, answer: "9"},
#   {question_id: 46, submission_id: 101, answer: "0"},
#   {question_id: 47, submission_id: 101, answer: "0"},
#   {question_id: 48, submission_id: 101, answer: "sdfdsf"},
#   {question_id: 49, submission_id: 101, answer: "sdfdsf"},
#   {question_id: 11, submission_id: 102, answer: "5"},
#   {question_id: 12, submission_id: 102, answer: "6"},
#   {question_id: 46, submission_id: 102, answer: "1"},
#   {question_id: 47, submission_id: 102, answer: "1"},
#   {question_id: 48, submission_id: 102, answer: "sdfdsf"},
#   {question_id: 49, submission_id: 102, answer: "sdfdsf"},
#   {question_id: 11, submission_id: 103, answer: "5"},
#   {question_id: 12, submission_id: 103, answer: "6"},
#   {question_id: 46, submission_id: 103, answer: "0"},
#   {question_id: 47, submission_id: 103, answer: "0"},
#   {question_id: 48, submission_id: 103, answer: "cvb"},
#   {question_id: 49, submission_id: 103, answer: "cvb"},
#   {question_id: 11, submission_id: 104, answer: "2"},
#   {question_id: 12, submission_id: 104, answer: "2"},
#   {question_id: 46, submission_id: 104, answer: "1"},
#   {question_id: 47, submission_id: 104, answer: "1"},
#   {question_id: 48, submission_id: 104, answer: "cvb"},
#   {question_id: 49, submission_id: 104, answer: "cvb"},
#   {question_id: 11, submission_id: 105, answer: "7"},
#   {question_id: 12, submission_id: 105, answer: "5"},
#   {question_id: 46, submission_id: 105, answer: "0"},
#   {question_id: 47, submission_id: 105, answer: "0"},
#   {question_id: 48, submission_id: 105, answer: "cccc"},
#   {question_id: 49, submission_id: 105, answer: "ccc"},
#   {question_id: 11, submission_id: 106, answer: "4"},
#   {question_id: 12, submission_id: 106, answer: "4"},
#   {question_id: 46, submission_id: 106, answer: "0"},
#   {question_id: 47, submission_id: 106, answer: "1"},
#   {question_id: 48, submission_id: 106, answer: "cccc"},
#   {question_id: 49, submission_id: 106, answer: "ccc"},
#   {question_id: 39, submission_id: 107, answer: "Orange"},
#   {question_id: 40, submission_id: 107, answer: "0"},
#   {question_id: 41, submission_id: 107, answer: "6"},
#   {question_id: 42, submission_id: 107, answer: "To Paris!"},
#   {question_id: 39, submission_id: 108, answer: "Blue"},
#   {question_id: 40, submission_id: 108, answer: "0"},
#   {question_id: 41, submission_id: 108, answer: "7"},
#   {question_id: 42, submission_id: 108, answer: "To Germany"},
#   {question_id: 39, submission_id: 109, answer: "Green"},
#   {question_id: 40, submission_id: 109, answer: "1"},
#   {question_id: 41, submission_id: 109, answer: "5"},
#   {question_id: 42, submission_id: 109, answer: "To Somalia"},
#   {question_id: 39, submission_id: 110, answer: "Green"},
#   {question_id: 40, submission_id: 110, answer: "1"},
#   {question_id: 41, submission_id: 110, answer: "10"},
#   {question_id: 42, submission_id: 110, answer: "To Japan"},
#   {question_id: 39, submission_id: 111, answer: "Orange"},
#   {question_id: 40, submission_id: 111, answer: "1"},
#   {question_id: 41, submission_id: 111, answer: "9"},
#   {question_id: 42, submission_id: 111, answer: "To Japan"},
#   {question_id: 39, submission_id: 112, answer: "Orange"},
#   {question_id: 40, submission_id: 112, answer: "1"},
#   {question_id: 41, submission_id: 112, answer: "2"},
#   {question_id: 42, submission_id: 112, answer: "To Japan"},
#   {question_id: 39, submission_id: 113, answer: "Blue"},
#   {question_id: 40, submission_id: 113, answer: "0"},
#   {question_id: 41, submission_id: 113, answer: "8"},
#   {question_id: 42, submission_id: 113, answer: "nowhere"},
#   {question_id: 39, submission_id: 114, answer: "Blue"},
#   {question_id: 40, submission_id: 114, answer: "1"},
#   {question_id: 41, submission_id: 114, answer: "7"},
#   {question_id: 42, submission_id: 114, answer: "nowhere"},
#   {question_id: 39, submission_id: 115, answer: "Orange"},
#   {question_id: 40, submission_id: 115, answer: "0"},
#   {question_id: 41, submission_id: 115, answer: "3"},
#   {question_id: 42, submission_id: 115, answer: "nowhere"},
#   {question_id: 27, submission_id: 116, answer: "to do stupid stuff"},
#   {question_id: 29, submission_id: 116, answer: "I love golf"},
#   {question_id: 27, submission_id: 117, answer: "for love"},
#   {question_id: 29, submission_id: 117, answer: "I love golf"},
#   {question_id: 27, submission_id: 118, answer: "to play ball"},
#   {question_id: 29, submission_id: 118, answer: "I hate golf"},
#   {question_id: 27, submission_id: 119, answer: "to do stupid stuff"},
#   {question_id: 29, submission_id: 119, answer: "I love golf"},
#   {question_id: 13, submission_id: 120, answer: "Somewhat"},
#   {question_id: 14, submission_id: 120, answer: "spaghetti"},
#   {question_id: 50, submission_id: 120, answer: "0"},
#   {question_id: 51, submission_id: 120, answer: "1"},
#   {question_id: 52, submission_id: 120, answer: "8"},
#   {question_id: 53, submission_id: 120, answer: "7"},
#   {question_id: 54, submission_id: 120, answer: "Yes of course!"},
#   {question_id: 55, submission_id: 120, answer: "Paris"},
#   {question_id: 13, submission_id: 121, answer: "No at all"},
#   {question_id: 14, submission_id: 121, answer: "spaghetti"},
#   {question_id: 50, submission_id: 121, answer: "0"},
#   {question_id: 51, submission_id: 121, answer: "1"},
#   {question_id: 52, submission_id: 121, answer: "6"},
#   {question_id: 53, submission_id: 121, answer: "8"},
#   {question_id: 54, submission_id: 121, answer: "Yes of course!"},
#   {question_id: 55, submission_id: 121, answer: "Paris"},
#   {question_id: 13, submission_id: 122, answer: "Somewhat"},
#   {question_id: 14, submission_id: 122, answer: "Casear Salad"},
#   {question_id: 50, submission_id: 122, answer: "0"},
#   {question_id: 51, submission_id: 122, answer: "1"},
#   {question_id: 52, submission_id: 122, answer: "4"},
#   {question_id: 53, submission_id: 122, answer: "2"},
#   {question_id: 54, submission_id: 122, answer: "Yes of course!"},
#   {question_id: 55, submission_id: 122, answer: "Paris"},
#   {question_id: 13, submission_id: 123, answer: "Very"},
#   {question_id: 14, submission_id: 123, answer: "spaghetti"},
#   {question_id: 50, submission_id: 123, answer: "1"},
#   {question_id: 51, submission_id: 123, answer: "0"},
#   {question_id: 52, submission_id: 123, answer: "2"},
#   {question_id: 53, submission_id: 123, answer: "5"},
#   {question_id: 54, submission_id: 123, answer: "Yes of course!"},
#   {question_id: 55, submission_id: 123, answer: "Paris"},
#   {question_id: 13, submission_id: 124, answer: "Somewhat"},
#   {question_id: 14, submission_id: 124, answer: "Casear Salad"},
#   {question_id: 50, submission_id: 124, answer: "0"},
#   {question_id: 51, submission_id: 124, answer: "0"},
#   {question_id: 52, submission_id: 124, answer: "10"},
#   {question_id: 53, submission_id: 124, answer: "10"},
#   {question_id: 54, submission_id: 124, answer: "What?"},
#   {question_id: 55, submission_id: 124, answer: "Your mom's house"},
#   {question_id: 13, submission_id: 125, answer: "No at all"},
#   {question_id: 14, submission_id: 125, answer: "spaghetti"},
#   {question_id: 50, submission_id: 125, answer: "0"},
#   {question_id: 51, submission_id: 125, answer: "0"},
#   {question_id: 52, submission_id: 125, answer: "2"},
#   {question_id: 53, submission_id: 125, answer: "3"},
#   {question_id: 54, submission_id: 125, answer: "What?"},
#   {question_id: 55, submission_id: 125, answer: "Your mom's house"},
#   {question_id: 13, submission_id: 126, answer: "Somewhat"},
#   {question_id: 14, submission_id: 126, answer: "spaghetti"},
#   {question_id: 50, submission_id: 126, answer: "0"},
#   {question_id: 51, submission_id: 126, answer: "0"},
#   {question_id: 52, submission_id: 126, answer: "5"},
#   {question_id: 53, submission_id: 126, answer: "9"},
#   {question_id: 54, submission_id: 126, answer: "What?"},
#   {question_id: 55, submission_id: 126, answer: "Your mom's house"},
#   {question_id: 13, submission_id: 127, answer: "Very"},
#   {question_id: 14, submission_id: 127, answer: "pizza"},
#   {question_id: 50, submission_id: 127, answer: "1"},
#   {question_id: 51, submission_id: 127, answer: "1"},
#   {question_id: 52, submission_id: 127, answer: "5"},
#   {question_id: 53, submission_id: 127, answer: "3"},
#   {question_id: 54, submission_id: 127, answer: "What?"},
#   {question_id: 55, submission_id: 127, answer: "Your mom's house"},
#   {question_id: 13, submission_id: 128, answer: "Somewhat"},
#   {question_id: 14, submission_id: 128, answer: "spaghetti"},
#   {question_id: 50, submission_id: 128, answer: "1"},
#   {question_id: 51, submission_id: 128, answer: "0"},
#   {question_id: 52, submission_id: 128, answer: "2"},
#   {question_id: 53, submission_id: 128, answer: "3"},
#   {question_id: 54, submission_id: 128, answer: "no"},
#   {question_id: 55, submission_id: 128, answer: "germany"},
#   {question_id: 13, submission_id: 129, answer: "Somewhat"},
#   {question_id: 14, submission_id: 129, answer: "Casear Salad"},
#   {question_id: 50, submission_id: 129, answer: "0"},
#   {question_id: 51, submission_id: 129, answer: "1"},
#   {question_id: 52, submission_id: 129, answer: "3"},
#   {question_id: 53, submission_id: 129, answer: "6"},
#   {question_id: 54, submission_id: 129, answer: "yes"},
#   {question_id: 55, submission_id: 129, answer: "Fiji"},
#   {question_id: 13, submission_id: 130, answer: "No at all"},
#   {question_id: 14, submission_id: 130, answer: "pizza"},
#   {question_id: 50, submission_id: 130, answer: "1"},
#   {question_id: 51, submission_id: 130, answer: "0"},
#   {question_id: 52, submission_id: 130, answer: "8"},
#   {question_id: 53, submission_id: 130, answer: "8"},
#   {question_id: 54, submission_id: 130, answer: "yes of course duh!"},
#   {question_id: 55, submission_id: 130, answer: "Japan"},
#   {question_id: 57, submission_id: 131, answer: "3"},
#   {question_id: 58, submission_id: 131, answer: "1"},
#   {question_id: 13, submission_id: 132, answer: "No at all"},
#   {question_id: 14, submission_id: 132, answer: "spaghetti"},
#   {question_id: 50, submission_id: 132, answer: "1"},
#   {question_id: 51, submission_id: 132, answer: "0"},
#   {question_id: 52, submission_id: 132, answer: "6"},
#   {question_id: 53, submission_id: 132, answer: "2"},
#   {question_id: 54, submission_id: 132, answer: "Oh Course"},
#   {question_id: 55, submission_id: 132, answer: "I don't know"},
#   {question_id: 13, submission_id: 133, answer: "No at all"},
#   {question_id: 14, submission_id: 133, answer: "spaghetti"},
#   {question_id: 50, submission_id: 133, answer: "0"},
#   {question_id: 51, submission_id: 133, answer: "0"},
#   {question_id: 52, submission_id: 133, answer: "4"},
#   {question_id: 53, submission_id: 133, answer: "5"},
#   {question_id: 54, submission_id: 133, answer: "Stuff"},
#   {question_id: 55, submission_id: 133, answer: "Coolness"},
#   {question_id: 38, submission_id: 134, answer: "b"},
#   {question_id: 31, submission_id: 135, answer: "Never"},
#   {question_id: 32, submission_id: 135, answer: "0"},
#   {question_id: 33, submission_id: 135, answer: "4"},
#   {question_id: 31, submission_id: 136, answer: "Never"},
#   {question_id: 32, submission_id: 136, answer: "0"},
#   {question_id: 33, submission_id: 136, answer: "9"},
#   {question_id: 3, submission_id: 137, answer: nil},
#   {question_id: 10, submission_id: 137, answer: nil},
#   {question_id: 19, submission_id: 138, answer: "Hey I bet this breaks things!"},
#   {question_id: 61, submission_id: 139, answer: "6"},
#   {question_id: 62, submission_id: 139, answer: "0"},
#   {question_id: 13, submission_id: 140, answer: "Somewhat"},
#   {question_id: 14, submission_id: 140, answer: "spaghetti"},
#   {question_id: 50, submission_id: 140, answer: "0"},
#   {question_id: 51, submission_id: 140, answer: "1"},
#   {question_id: 52, submission_id: 140, answer: "3"},
#   {question_id: 53, submission_id: 140, answer: "6"},
#   {question_id: 54, submission_id: 140, answer: "stuff"},
#   {question_id: 55, submission_id: 140, answer: "nowhere"},
#   {question_id: 13, submission_id: 141, answer: "No at all"},
#   {question_id: 14, submission_id: 141, answer: "pizza"},
#   {question_id: 50, submission_id: 141, answer: "1"},
#   {question_id: 51, submission_id: 141, answer: "0"},
#   {question_id: 52, submission_id: 141, answer: "4"},
#   {question_id: 53, submission_id: 141, answer: "6"},
#   {question_id: 54, submission_id: 141, answer: "stuff"},
#   {question_id: 55, submission_id: 141, answer: "nowhere"},
#   {question_id: 13, submission_id: 142, answer: "Somewhat"},
#   {question_id: 14, submission_id: 142, answer: "Casear Salad"},
#   {question_id: 50, submission_id: 142, answer: "1"},
#   {question_id: 51, submission_id: 142, answer: "0"},
#   {question_id: 52, submission_id: 142, answer: "4"},
#   {question_id: 53, submission_id: 142, answer: "6"},
#   {question_id: 54, submission_id: 142, answer: "stuff"},
#   {question_id: 55, submission_id: 142, answer: "nowhere"},
#   {question_id: 13, submission_id: 143, answer: "Somewhat"},
#   {question_id: 14, submission_id: 143, answer: "spaghetti"},
#   {question_id: 50, submission_id: 143, answer: "0"},
#   {question_id: 51, submission_id: 143, answer: "1"},
#   {question_id: 52, submission_id: 143, answer: "4"},
#   {question_id: 53, submission_id: 143, answer: "5"},
#   {question_id: 54, submission_id: 143, answer: "stuff"},
#   {question_id: 55, submission_id: 143, answer: "coolness"},
#   {question_id: 61, submission_id: 144, answer: "2"},
#   {question_id: 62, submission_id: 144, answer: "0"},
#   {question_id: 61, submission_id: 145, answer: "9"},
#   {question_id: 62, submission_id: 145, answer: "0"},
#   {question_id: 19, submission_id: 146, answer: "This is gonna break..."},
#   {question_id: 19, submission_id: 147, answer: "This, surely...."},
#   {question_id: 3, submission_id: 148, answer: nil},
#   {question_id: 10, submission_id: 148, answer: nil},
#   {question_id: 3, submission_id: 149, answer: nil},
#   {question_id: 10, submission_id: 149, answer: nil}
# ])
# Evaluation.create!([
#   {template_id: 9, teacher_id: 2, url: nil, subject: nil, message: nil},
#   {template_id: 2, teacher_id: 4, url: nil, subject: nil, message: nil},
#   {template_id: 12, teacher_id: 2, url: "C72A12D3", subject: nil, message: nil},
#   {template_id: 9, teacher_id: 4, url: nil, subject: nil, message: nil},
#   {template_id: 9, teacher_id: 4, url: nil, subject: nil, message: nil},
#   {template_id: 12, teacher_id: 1, url: nil, subject: nil, message: nil},
#   {template_id: 9, teacher_id: 4, url: nil, subject: nil, message: nil},
#   {template_id: 9, teacher_id: 2, url: "0", subject: nil, message: nil},
#   {template_id: 9, teacher_id: 2, url: "0", subject: nil, message: nil},
#   {template_id: 1, teacher_id: 1, url: "E31DAA47", subject: nil, message: nil},
#   {template_id: 15, teacher_id: 2, url: "C460CDFB", subject: nil, message: nil},
#   {template_id: 15, teacher_id: 1, url: "AA527BAF", subject: nil, message: nil},
#   {template_id: 15, teacher_id: 1, url: "AA527BAG", subject: nil, message: nil},
#   {template_id: 4, teacher_id: 7, url: "D124495D", subject: nil, message: nil},
#   {template_id: 11, teacher_id: 7, url: "FDAE7333", subject: nil, message: nil},
#   {template_id: 13, teacher_id: 7, url: "1B5AE8EE", subject: nil, message: nil},
#   {template_id: 13, teacher_id: 8, url: "16735280", subject: nil, message: nil},
#   {template_id: 13, teacher_id: 7, url: "E2CDEB75", subject: nil, message: nil},
#   {template_id: 13, teacher_id: 8, url: "7957D3F3", subject: nil, message: nil},
#   {template_id: 13, teacher_id: 8, url: "CC563B28", subject: nil, message: nil},
#   {template_id: 13, teacher_id: 7, url: "D7DBCEAE", subject: nil, message: nil},
#   {template_id: 14, teacher_id: 7, url: "30177601", subject: nil, message: nil},
#   {template_id: 14, teacher_id: 8, url: "721890C7", subject: nil, message: nil},
#   {template_id: 14, teacher_id: 7, url: "A4AFCAD0", subject: nil, message: nil},
#   {template_id: 14, teacher_id: 7, url: "371270B8", subject: nil, message: nil},
#   {template_id: 14, teacher_id: 8, url: "F8F8CB63", subject: nil, message: nil},
#   {template_id: 11, teacher_id: 7, url: "B9FBF2DA", subject: nil, message: nil},
#   {template_id: 11, teacher_id: 7, url: "F45A8E06", subject: nil, message: nil},
#   {template_id: 16, teacher_id: 7, url: "8B7CCD6D", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 7, url: "6D4B3A4F", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 8, url: "602C4F5A", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 7, url: "F0F329DD", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 8, url: "14A75DC6", subject: nil, message: nil},
#   {template_id: 19, teacher_id: 10, url: "B05263C7", subject: "This is a test", message: "Here's the message!"},
#   {template_id: 10, teacher_id: 11, url: "456FEA29", subject: nil, message: nil},
#   {template_id: 9, teacher_id: 11, url: "AB0CF237", subject: nil, message: nil},
#   {template_id: 9, teacher_id: 8, url: "F8E2E447", subject: nil, message: nil},
#   {template_id: 4, teacher_id: 7, url: "FF235E32", subject: nil, message: nil},
#   {template_id: 21, teacher_id: 11, url: "82B23795", subject: nil, message: nil},
#   {template_id: 23, teacher_id: 7, url: "88422225", subject: nil, message: nil},
#   {template_id: 23, teacher_id: 8, url: "115030BB", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 7, url: "176C29C4", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 11, url: "10EBF166", subject: nil, message: nil},
#   {template_id: 26, teacher_id: 12, url: "26D17CC3", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 11, url: "3C799355", subject: nil, message: nil},
#   {template_id: 17, teacher_id: 7, url: "BBDC1F03", subject: nil, message: nil},
#   {template_id: 4, teacher_id: 7, url: "BB838C75", subject: nil, message: nil},
#   {template_id: 29, teacher_id: 7, url: "AED7E4C0", subject: nil, message: nil},
#   {template_id: 30, teacher_id: 13, url: "B874FED1", subject: nil, message: nil},
#   {template_id: 23, teacher_id: 7, url: "8381FEC9", subject: nil, message: nil},
#   {template_id: 23, teacher_id: 8, url: "A7677C74", subject: nil, message: nil},
#   {template_id: 21, teacher_id: 11, url: "5BAE63A7", subject: nil, message: nil},
#   {template_id: 21, teacher_id: 8, url: "2A650C3A", subject: nil, message: nil},
#   {template_id: 4, teacher_id: 7, url: "060B8EFE", subject: nil, message: nil},
#   {template_id: 4, teacher_id: 7, url: "FA7A4A42", subject: "sdsdfsdf", message: "sdfsdfdf"},
#   {template_id: 4, teacher_id: 7, url: "66166826", subject: "dsdfsdfsd", message: "hee's a message"}
# ])
# Question.create!([
#   {text: "Did you like the instructor?", template_id: 12, required: false, format_type: "text"},
#   {text: "Was he/she available during office hours?", template_id: 12, required: true, format_type: "1"},
#   {text: "yo", template_id: 4, required: true, format_type: "ranking"},
#   {text: "Is he/she a good instructor?", template_id: 1, required: true, format_type: "text"},
#   {text: "Did he/she give you homework?", template_id: 1, required: false, format_type: "multipleChoice"},
#   {text: "What's your fav color?", template_id: 6, required: false, format_type: "ranking"},
#   {text: "Why did you take this class?", template_id: 6, required: true, format_type: "text"},
#   {text: "Good teacher?", template_id: 7, required: false, format_type: "multipleChoice"},
#   {text: "Bad Breath?", template_id: 7, required: true, format_type: "multipleChoice"},
#   {text: "Here's another question.", template_id: 4, required: true, format_type: "ranking"},
#   {text: "How knowledgeable was the instructor?", template_id: 12, required: true, format_type: "1"},
#   {text: "Would you recommend him/her to other students?", template_id: 12, required: false, format_type: "text"},
#   {text: "Did you like the accompanying course packet/book?", template_id: 12, required: true, format_type: "ranking"},
#   {text: "Scale of 1 to 10, How good was the instructor?\n", template_id: 15, required: true, format_type: "scale1To10"},
#   {text: "Scale of 1 to 10, how useful were the homework assignments?", template_id: 15, required: false, format_type: "scale1To10"},
#   {text: "Scale of 1 to 10, How knowledgable was the intructor?", template_id: 15, required: true, format_type: "scale1To10"},
#   {text: "Scale of 1 to 10, How useful were the in-class exercises?", template_id: 15, required: true, format_type: "scale1To10"},
#   {text: "Did you do the homework?", template_id: 15, required: false, format_type: "boolean"},
#   {text: "Would you recommend this course to colleagues?", template_id: 15, required: true, format_type: "boolean"},
#   {text: "Who was your TA?", template_id: 15, required: true, format_type: "multipleChoice"},
#   {text: "How likely would you take the course again?", template_id: 9, required: nil, format_type: "multipleChoice"},
#   {text: "Did you like your instructor?", template_id: 9, required: false, format_type: "boolean"},
#   {text: "How knowledgable did you find the instructor?", template_id: 9, required: nil, format_type: "scale1To10"},
#   {text: "Here's a question", template_id: 10, required: nil, format_type: "multipleChoice"},
#   {text: "What's your favorite color?", template_id: 11, required: true, format_type: "multipleChoice"},
#   {text: "Are you male?", template_id: 11, required: nil, format_type: "boolean"},
#   {text: "How much do you like San Francisco weather?", template_id: 11, required: true, format_type: "scale1To10"},
#   {text: "If you were a bird, where would you go?", template_id: 11, required: true, format_type: "text"},
#   {text: "What are you doing tonight?", template_id: 13, required: nil, format_type: "multipleChoice"},
#   {text: "How cool is Star Trek?", template_id: 13, required: true, format_type: "scale1To10"},
#   {text: "Would you ever learn the trumpet?", template_id: 13, required: true, format_type: "boolean"},
#   {text: "Was she a good teacher?", template_id: 14, required: true, format_type: "scale1To10"},
#   {text: "Did she understand the material well?", template_id: 14, required: true, format_type: "scale1To10"},
#   {text: "Are you from the land down under?", template_id: 14, required: true, format_type: "boolean"},
#   {text: "Is there thunder?", template_id: 14, required: true, format_type: "boolean"},
#   {text: "What's best about it?", template_id: 14, required: true, format_type: "text"},
#   {text: "No really tell me?", template_id: 14, required: nil, format_type: "text"},
#   {text: "Why did you take the course?", template_id: 16, required: true, format_type: "multipleChoice"},
#   {text: "Where do you like to play golf", template_id: 16, required: true, format_type: "multipleChoice"},
#   {text: "How Knowledgable was he/she?", template_id: 17, required: true, format_type: "multipleChoice"},
#   {text: "What do you like?", template_id: 17, required: true, format_type: "multipleChoice"},
#   {text: "Have you been to Rio?", template_id: 17, required: true, format_type: "boolean"},
#   {text: "Is water harmful?", template_id: 17, required: nil, format_type: "boolean"},
#   {text: "How awesome is pizza?", template_id: 17, required: true, format_type: "scale1To10"},
#   {text: "How much do you like the French?", template_id: 17, required: nil, format_type: "scale1To10"},
#   {text: "Moby Dick. Fan?", template_id: 17, required: nil, format_type: "text"},
#   {text: "Where in the world is Carmen Sandiego?", template_id: 17, required: true, format_type: "text"},
#   {text: "Where do babies come from?", template_id: 18, required: false, format_type: "text"},
#   {text: "How much do you like pizza?", template_id: 18, required: true, format_type: "scale1To10"},
#   {text: "Where do you come from?", template_id: 19, required: true, format_type: "scale1To10"},
#   {text: "Are you a cat or dog person?", template_id: 19, required: nil, format_type: "boolean"},
#   {text: "Where are you from? Please explain", template_id: 20, required: nil, format_type: "text"},
#   {text: "How hot is Kirsten Dunst?", template_id: 20, required: true, format_type: "scale1To10"},
#   {text: "Let's see what this breaks!", template_id: 21, required: false, format_type: "text"},
#   {text: "foo", template_id: nil, required: true, format_type: "multipleChoice"},
#   {text: "How much do you like Las Vegas?", template_id: 23, required: nil, format_type: "scale1To10"},
#   {text: "Are you happy?", template_id: 23, required: true, format_type: "boolean"},
#   {text: "What?", template_id: 30, required: true, format_type: "scale1To10"},
#   {text: "why?", template_id: 24, required: true, format_type: "multipleChoice"},
#   {text: "this work?", template_id: 24, required: true, format_type: "boolean"},
#   {text: "You bugged me!", template_id: 24, required: true, format_type: "text"},
#   {text: "Why do we do this?", template_id: 26, required: true, format_type: "multipleChoice"},
#   {text: "How much do you like Young Frankenstein?", template_id: 26, required: true, format_type: "scale1To10"},
#   {text: "What's the meaning of life?", template_id: 26, required: false, format_type: "text"},
#   {text: "Are you happy?", template_id: 26, required: true, format_type: "boolean"},
#   {text: "stuff", template_id: 27, required: true, format_type: "multipleChoice"},
#   {text: "what do you like?", template_id: 28, required: true, format_type: "scale1To10"},
#   {text: "You like it?", template_id: 28, required: true, format_type: "boolean"},
#   {text: "Which?", template_id: 28, required: true, format_type: "multipleChoice"},
#   {text: "What's the best?", template_id: 28, required: false, format_type: "text"},
#   {text: "sdfsdf", template_id: 29, required: true, format_type: "scale1To10"},
#   {text: "zxczxc", template_id: 29, required: true, format_type: "boolean"},
#   {text: "zczxc", template_id: 29, required: true, format_type: "scale1To10"},
#   {text: "Are you happy?", template_id: 30, required: true, format_type: "boolean"},
#   {text: "fruit?", template_id: 30, required: true, format_type: "multipleChoice"},
#   {text: "Love, what is it good for?", template_id: 30, required: true, format_type: "text"},
#   {text: "stuff", template_id: 31, required: true, format_type: "boolean"},
#   {text: "neato", template_id: 31, required: true, format_type: "boolean"},
#   {text: "neato", template_id: 31, required: true, format_type: "boolean"},
#   {text: "asdasd", template_id: 32, required: true, format_type: "boolean"},
#   {text: "Test", template_id: 34, required: true, format_type: "boolean"},
#   {text: "Here you go", template_id: 35, required: true, format_type: "boolean"},
#   {text: "stuff", template_id: 36, required: true, format_type: "multipleChoice"},
#   {text: "Does it work?", template_id: 37, required: true, format_type: "boolean"},
#   {text: "Where are they?", template_id: 37, required: true, format_type: "scale1To10"},
#   {text: "asdfsdf", template_id: 37, required: true, format_type: "scale1To10"},
#   {text: "sdsd", template_id: 37, required: true, format_type: "multipleChoice"}
# ])
# QuestionOption.create!([
#   {question_id: 607, text: "Carl"},
#   {question_id: 607, text: "Suzzy"},
#   {question_id: 607, text: "Diego"},
#   {question_id: 77, text: "asdf"},
#   {question_id: 77, text: "ouiioio"},
#   {question_id: 31, text: "Absolutely"},
#   {question_id: 31, text: "Never"},
#   {question_id: 77, text: "asdasdsd"},
#   {question_id: 80, text: "bananas"},
#   {question_id: 80, text: "oranges"},
#   {question_id: 80, text: "pineapples"},
#   {question_id: 87, text: "banana"},
#   {question_id: 87, text: "strawberry"},
#   {question_id: 87, text: "orange"},
#   {question_id: 95, text: "sdfsdf"},
#   {question_id: 95, text: "sdsdf"},
#   {question_id: 99, text: "sdfsd"},
#   {question_id: 38, text: "a"},
#   {question_id: 38, text: "b"},
#   {question_id: 39, text: "Green"},
#   {question_id: 39, text: "Blue"},
#   {question_id: 39, text: "Orange"},
#   {question_id: 43, text: "watching a movie"},
#   {question_id: 43, text: "playing card games"},
#   {question_id: 43, text: "nothing"},
#   {question_id: 27, text: "to play ball"},
#   {question_id: 27, text: "to do stupid stuff"},
#   {question_id: 29, text: "I hate golf"},
#   {question_id: 29, text: "I love golf"},
#   {question_id: 27, text: "for love"},
#   {question_id: 13, text: "Very"},
#   {question_id: 13, text: "No at all"},
#   {question_id: 13, text: "Somewhat"},
#   {question_id: 14, text: "pizza"},
#   {question_id: 14, text: "spaghetti"},
#   {question_id: 14, text: "Casear Salad"},
#   {question_id: 68, text: "radness"},
#   {question_id: 68, text: "because"}
# ])
# Respondent.create!([
#   {first_name: "Mark", last_name: "Richardson", email: "markebafdn@yahoo.com", responded: nil, evaluation_id: 19, emailed: true, unsubscribed_to_user: true, unsubscribed_to_all: true},
#   {first_name: "Mark", last_name: "Richardson", email: "markfeba1n@yahoo.com", responded: true, evaluation_id: 38, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markedban2@yahoo.com", responded: nil, evaluation_id: 46, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markeban3@yahoo.com", responded: nil, evaluation_id: 48, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markebgan4@yahoo.com", responded: nil, evaluation_id: 63, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markebganr5@gmail.com", responded: nil, evaluation_id: 63, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: nil, last_name: nil, email: "stufff@dssdf.com", responded: nil, evaluation_id: 64, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markebfan6@yahoo.com", responded: true, evaluation_id: 64, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markebadn7@yahoo.com", responded: nil, evaluation_id: 65, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markesddfsban7@yahoo.com", responded: nil, evaluation_id: 65, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: "Mark", last_name: "Richardson", email: "markedban7r@gmail.com", responded: nil, evaluation_id: 65, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: nil, last_name: nil, email: "sfsdfgff@ssdf.com", responded: nil, evaluation_id: 65, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil},
#   {first_name: nil, last_name: nil, email: "sdsadfdggf@dsfdsf.com", responded: nil, evaluation_id: 65, emailed: true, unsubscribed_to_user: nil, unsubscribed_to_all: nil}
# ])
# Submission.create!([
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 3, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 14, user_id: nil},
#   {evaluation_id: 16, user_id: nil},
#   {evaluation_id: 16, user_id: nil},
#   {evaluation_id: 16, user_id: nil},
#   {evaluation_id: 16, user_id: nil},
#   {evaluation_id: 16, user_id: nil},
#   {evaluation_id: 16, user_id: nil},
#   {evaluation_id: 16, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 17, user_id: nil},
#   {evaluation_id: 19, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 20, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 21, user_id: nil},
#   {evaluation_id: 22, user_id: nil},
#   {evaluation_id: 22, user_id: nil},
#   {evaluation_id: 22, user_id: nil},
#   {evaluation_id: 22, user_id: nil},
#   {evaluation_id: 23, user_id: nil},
#   {evaluation_id: 23, user_id: nil},
#   {evaluation_id: 23, user_id: nil},
#   {evaluation_id: 23, user_id: nil},
#   {evaluation_id: 24, user_id: nil},
#   {evaluation_id: 24, user_id: nil},
#   {evaluation_id: 24, user_id: nil},
#   {evaluation_id: 25, user_id: nil},
#   {evaluation_id: 25, user_id: nil},
#   {evaluation_id: 25, user_id: nil},
#   {evaluation_id: 26, user_id: nil},
#   {evaluation_id: 26, user_id: nil},
#   {evaluation_id: 26, user_id: nil},
#   {evaluation_id: 27, user_id: nil},
#   {evaluation_id: 27, user_id: nil},
#   {evaluation_id: 28, user_id: nil},
#   {evaluation_id: 28, user_id: nil},
#   {evaluation_id: 29, user_id: nil},
#   {evaluation_id: 29, user_id: nil},
#   {evaluation_id: 30, user_id: nil},
#   {evaluation_id: 30, user_id: nil},
#   {evaluation_id: 31, user_id: nil},
#   {evaluation_id: 31, user_id: nil},
#   {evaluation_id: 31, user_id: nil},
#   {evaluation_id: 31, user_id: nil},
#   {evaluation_id: 31, user_id: nil},
#   {evaluation_id: 31, user_id: nil},
#   {evaluation_id: 32, user_id: nil},
#   {evaluation_id: 32, user_id: nil},
#   {evaluation_id: 32, user_id: nil},
#   {evaluation_id: 33, user_id: nil},
#   {evaluation_id: 33, user_id: nil},
#   {evaluation_id: 33, user_id: nil},
#   {evaluation_id: 33, user_id: nil},
#   {evaluation_id: 34, user_id: nil},
#   {evaluation_id: 34, user_id: nil},
#   {evaluation_id: 34, user_id: nil},
#   {evaluation_id: 34, user_id: nil},
#   {evaluation_id: 35, user_id: nil},
#   {evaluation_id: 35, user_id: nil},
#   {evaluation_id: 35, user_id: nil},
#   {evaluation_id: 35, user_id: nil},
#   {evaluation_id: 36, user_id: nil},
#   {evaluation_id: 37, user_id: nil},
#   {evaluation_id: 37, user_id: nil},
#   {evaluation_id: 38, user_id: nil},
#   {evaluation_id: 39, user_id: nil},
#   {evaluation_id: 40, user_id: nil},
#   {evaluation_id: 41, user_id: nil},
#   {evaluation_id: 42, user_id: nil},
#   {evaluation_id: 43, user_id: nil},
#   {evaluation_id: 44, user_id: nil},
#   {evaluation_id: 45, user_id: nil},
#   {evaluation_id: 47, user_id: nil},
#   {evaluation_id: 50, user_id: nil},
#   {evaluation_id: 50, user_id: nil},
#   {evaluation_id: 50, user_id: nil},
#   {evaluation_id: 51, user_id: nil},
#   {evaluation_id: 59, user_id: nil},
#   {evaluation_id: 60, user_id: nil},
#   {evaluation_id: 61, user_id: nil},
#   {evaluation_id: 62, user_id: nil},
#   {evaluation_id: 64, user_id: nil},
#   {evaluation_id: 64, user_id: nil}
# ])
# Subscription.create!([
#   {user_id: 1, braintree_customer_id: 27345048, braintree_subscription_id: "bdnxrm"}
# ])
# Teacher.create!([
#   {email: "jpat@gmail.com", user_id: nil, name: "Joan Paterson"},
#   {email: "timshumate@tim.com", user_id: nil, name: "Tim Shumate"},
#   {email: "stuff@you.com", user_id: nil, name: "Sally Suthers"},
#   {email: "chris1492@gmail.com", user_id: nil, name: "Christopher  Columbus"},
#   {email: "mrichardson@yahoo.com", user_id: nil, name: "Mark Richardson"},
#   {email: "mrichardson@yahoo.com", user_id: nil, name: "Mark Richardson"},
#   {email: "jdoe@gmail.com", user_id: 1, name: "John Doe"},
#   {email: "scarlton@gmail.com", user_id: 1, name: "Sally Carlton"},
#   {email: "fgroup@gmail.com", user_id: 2, name: "Focus Group 1"},
#   {email: "markeban@yahoo.com", user_id: 1, name: "Mark Richardson"},
#   {email: "testtest@gmail.com", user_id: 6, name: "test test"},
#   {email: "sam@gmail.com", user_id: 7, name: "John Samsung"}
# ])
# Template.create!([
#   {name: "Evening Teacher Template", user_id: "2"},
#   {name: "Special Education Teacher Template", user_id: "2"},
#   {name: "Johnny Lee's Other English Class", user_id: "2"},
#   {name: "Early classes", user_id: "1"},
#   {name: "Children 12-14 yrs", user_id: "1"},
#   {name: "Polling Graph Questions", user_id: "1"},
#   {name: "Let's Use Angular!", user_id: "1"},
#   {name: "angular again", user_id: "1"},
#   {name: "Engineer Classes", user_id: "1"},
#   {name: "Another Test", user_id: "1"},
#   {name: "Formal Test", user_id: "1"},
#   {name: "delete_me", user_id: "1"},
#   {name: "July_16_test", user_id: "1"},
#   {name: "Multiple Scale Questions", user_id: "1"},
#   {name: "pie charts", user_id: "1"},
#   {name: "All Types ", user_id: "1"},
#   {name: "Test different user survey", user_id: "2"},
#   {name: "New User test", user_id: "2"},
#   {name: "ONLY TEXT", user_id: "1"},
#   {name: "Fix Question", user_id: "1"},
#   {name: "Seth Demo", user_id: "1"},
#   {name: "Fix Required quantitative questions", user_id: "1"},
#   {name: "blank question texts", user_id: "1"},
#   {name: "test again", user_id: "6"},
#   {name: "Stuff", user_id: "1"},
#   {name: "zxxczxc", user_id: "1"},
#   {name: "Dry Run", user_id: "7"},
#   {name: "Test Delete", user_id: "1"},
#   {name: "Test Delete", user_id: "1"},
#   {name: "test gain", user_id: "1"},
#   {name: "Test", user_id: "1"},
#   {name: "firefox test", user_id: "1"},
#   {name: "Safari Test", user_id: "1"},
#   {name: "google test", user_id: "1"}
# ])
